/*
Here we will talk about the javascript features you can use in react native and the ones you cannot use....
It is recommended to always check the article on https://facebook.github.io/react-native/docs/javascript-environment from time to time in other to know the available javascript features you can use.... It is advisable to do this from time to time because react native is evolving and so things change rapidly...
*/
